networks:
  server:

services:
  server:
    container_name: url-shortener-server
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./upload:/upload
    ports:
      - '3010:3000'
    restart: always

    networks:
      - server
